# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: sadhukhandeepan@gmail.com
author_name: DeepanIsCool
contract_name: solyrix_algorand
deployment_language: python
preset_name: starter
project_name: Solyrix-Algorand-contracts

